apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-generator
spec:
  selector:
    matchLabels:
      app: pod-generator
  template:
    metadata:
      labels:
        app: pod-generator
    spec:
      containers:
      - env:
          - name: RUST_LOG
            value: debug
          - name: LINKERD_INJECT
            value: "true"
          - name: INSTANCE_IMAGE
            value: "instance-service-0.1.0-7"
          - name: SIEVE_IMAGE
            value: "prime-sieve-0.1.0-6"
          - name: CONTAINER_REGISTRY_BASE_PATH
            value: "amartest.azurecr.io/apps/slb"
        name: pod-generator
        image: amartest.azurecr.io/apps/slb/pod-generator:0.1.0-17
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: generator-service
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: pod-generator
  type: ClusterIP